include: configs/base.yaml
tabnet:
  max_epochs: 20
  patience: 10
  batch_size: 512
  virtual_batch_size: 128
  params:
    n_d: 32
    n_a: 32
    n_steps: 5
    gamma: 1.5
    lambda_sparse: 0.00001
    lr: 0.001
    weight_decay: 0.00001

