include: configs/base.yaml
tabnet:
  max_epochs: 50
  patience: 10
  batch_size: 512
  virtual_batch_size: 128
  optimizer: adam
  loss: weighted_ce
  tune:
    n_trials: 5
    params:
      n_d: [16, 32]
      n_a: [16, 32]
      n_steps: [3, 5]
      gamma: [1.0, 1.5]
      lambda_sparse: {loguniform: [1.0e-06, 1.0e-03]}
      lr: {loguniform: [0.0001, 0.001]}
      weight_decay: {loguniform: [1.0e-06, 1.0e-04]}

